//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransformationRuleModelText
    {
        public int Id { get; set; }
        public string Final { get; set; }
        public int TransformationModelTextId { get; set; }
    
        public virtual TransformationModelText TransformationModelText { get; set; }
        public virtual Entity Initial { get; set; }
    }
}
