//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransformationRuleModelModel
    {
        public int Id { get; set; }
        public int TransformationModelModelId { get; set; }
    
        public virtual TransformationModelModel TransformationModelModel { get; set; }
        public virtual Entity Initial { get; set; }
        public virtual Entity Final { get; set; }
    }
}
